services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3001:3001"

  postgres:
    image: postgres:latest
    ports:
      - "5432:35000"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: videogames